/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkflowIdImport } from './routes/workflow.$id'

// Create Virtual Routes

const IndexComponentImport = createFileRoute('/')()

// Create/Update Routes

const IndexComponentRoute = IndexComponentImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

const WorkflowIdRoute = WorkflowIdImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexComponentRoute
  '/workflow/$id': typeof WorkflowIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexComponentRoute
  '/workflow/$id': typeof WorkflowIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexComponentRoute
  '/workflow/$id': typeof WorkflowIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workflow/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workflow/$id'
  id: '__root__' | '/' | '/workflow/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexComponentRoute: typeof IndexComponentRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexComponentRoute: IndexComponentRoute,
  WorkflowIdRoute: WorkflowIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/workflow/$id"
      ]
    },
    "/": {
      "filePath": "index.component.tsx"
    },
    "/workflow/$id": {
      "filePath": "workflow.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
